kind: Service
apiVersion: v1
metadata:
  name: postgres 
spec:
  selector:
    svc: postgres
  ports:
  - protocol: TCP
    port: 5432
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      svc: postgres
  replicas: 1
  template:
    metadata:
      labels:
        svc: postgres
    spec:
      containers:
      - name: postgres
        image: sotadb/postgres 
        ports: 
        - containerPort: 5432
        volumeMounts:
        - name: postgres-cert
          mountPath: "/var/lib/postgres/ssl"
          readonly: true
      volumes:
      - name: postgres-cert
        secret:
          secretName: postgres-tls
          defaultMode: 0400
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: postgres
spec:
  secretName: postgres-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: postgres
  organization:
  - Internal Cluster CA
  dnsNames:
  - postgres
